# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 14156c998ba49f04d5ea9d7df98319bcad5cc324d46b0a9810c7df97a2ef4e9ae7d5f6b92f8c1858a309c5ae668d1618d385b4378702b7ff95a7df5d0a771198

test:
  secret_key_base: 8e662b9346176ee91d2ff53718acfd6d125253397d3c5bac2caed09b8736ae841b3e70256eba44df65a5e8dc4446c05e50d2c161c6988191db48a8dfd3383ea7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
